name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-test:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [20, 22]

    steps:
      - uses: actions/checkout@v3

      - name: Fetch main branch
        run: git fetch origin main:main || true
        shell: bash

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Git Truck
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Clear git-truck cache
        run: |
          if [ -d "$TMPDIR/git-truck-cache" ]; then
            rm -rf "$TMPDIR/git-truck-cache"
          fi
          if [ -d "/tmp/git-truck-cache" ]; then
            rm -rf "/tmp/git-truck-cache"
          fi
        shell: bash

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.os }}-node-${{ matrix.node }}
          path: playwright-report/
          retention-days: 30
